### ISSUE TITLE
Create the Compact Group Component

### ISSUE THREAD

**Issue by SilveerDusk** [SilveerDusk/Target-Share#14]
**User Story**
As an organizer, I’d like to be able to see all the events I am planning and the items that individuals are bringing when I’m planning events, so that I can keep track of who’s bringing what, how much money each item costs, and keep things equitable. (Jonathan Hagendoorn)

**Description**
Create the Compact Group Component that will go on the group page
![Image](https://github.com/SilveerDusk/Gather/assets/114632851/f0123a4d-8648-41c0-b2b7-9d929cf44250)

**Acceptance Criteria**
- matches the figma design
- use dummy data to create a component, (does not need to be connected to mongodb yet)

**Additional Information**
Check these out: [UI Lib](https://v2.chakra-ui.com/docs/components)

**Comment by jhcsdev** [comment]
yeah again i made a suuuper basic component, no colors and lotta data missing, but we can add allat later
