### ISSUE TITLE
Create the Compact Item Component

### ISSUE THREAD

**Issue by SilveerDusk** [SilveerDusk/Target-Share#15]
**User Story**
As an inspector, I want to see the details of a specific item that I own or is shared with me, so that I can better understand its condition and/or value. (Zach Mattes)

**Description**
Create the Compact Item Component so that we can display all of the properties of an item
![Image](https://github.com/SilveerDusk/Gather/assets/114632851/2d7b2a53-083b-4469-a180-5320ddd3257d)

**Acceptance Criteria**
- design matches the figma
- use dummy data to create a filled out component, (does not have to be connected to db yet)

**Additional Information**
Check these out: [UI Lib](https://v2.chakra-ui.com/docs/components)

**Comment by jhcsdev** [comment]
yeah i'm basically done w this, i added the edit option but you can't edit anything yet bc that's gonna be a later thing, editing stuff is gonna be waaaay harder than just making the base layout

**Comment by palldas** [comment]
sorry i was moving random stuff around cuz i was zoned out and didn't realize it logged where i was moving it and closed this issue automatically lmao
