### ISSUE TITLE
Create the My Groups Page

### ISSUE THREAD

**Issue by SilveerDusk** [SilveerDusk/Target-Share#16]
**User Story**
As an organizer, I’d like to be able to see all the events I am planning and the items that individuals are bringing when I’m planning events, so that I can keep track of who’s bringing what, how much money each item costs, and keep things equitable. (Jonathan Hagendoorn)

**Description**
Create a groups page that looks similar to the figma. Instead of displaying the groups, add centered text that says "no groups yet" or something like that.
![Image](https://github.com/SilveerDusk/Gather/assets/114632851/2e479fd1-d2fb-49ac-a707-8c0f4646397f)

**Acceptance Criteria**
- Groups page looks similar to figma
- Search bar is there but not functional
- Buttons to create groups and invite members are there as in figma but not functional
- Button/Hyperlink to switch to the items page (/items) is there but should take you to a 404 since the items page wont be build yet

Steps:
Feel free to add your own or let me know, but follow the figma for now.

**Additional Information**

**Comment by jhcsdev** [comment]
2.5 hr spent so far

**Comment by jhcsdev** [comment]
THIS IS GOING TO TAKE CONSIDERABLY LONGER THAN I THOUGHT 💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀

**Comment by jhcsdev** [comment]
Also this took a total of about 5 or 6 hours because I am super indecisive on UI and spent way longer than I should have getting something I liked lol
