### ISSUE TITLE
Create the Send Invite Component

### ISSUE THREAD

**Issue by palldas** [SilveerDusk/Target-Share#33]
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:
- step 1
- step 2

**Additional Information**

**Comment by jhcsdev** [comment]
i'm working on this as part of the my groups page! makes it easier for me to plan out UI and stuff. if anyone wants to take over lmk!

**Comment by jhcsdev** [comment]
passing this off to @palldas 
i recommend checking out #25 for the basic popout structure and mimicking that to give the design some continuity
