### ISSUE TITLE
Create workspaces + fix package locks

### ISSUE THREAD

**Issue by jhcsdev** [SilveerDusk/Target-Share#35]

**Comment by jhcsdev** [comment]
aight i tried doing this and it simply is impossible to be 100% certain that I'm migrating everything correctly, i think it's fine if we just leave it as is since i was the main person advocating for this anyway lol

**Comment by SilveerDusk** [comment]
Fair enough,
I think our solution can just to have three terminals constantly open, one for backend, one for the front end, and one for git.
