### ISSUE TITLE
User Auth Teams Assignment

### ISSUE THREAD

**Issue by SilveerDusk** [SilveerDusk/Target-Share#40]
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:
- step 1
- step 2

**Additional Information**

**Comment by jhcsdev** [comment]
is this going to be what connects a user to the frontend? there are a lot of functions that require userId on frontend so I think we should bump this up in priority, or if this isn't what would load a userId on frontend we need to bump that task up

**Comment by SilveerDusk** [comment]
working on it rn

**Comment by jhcsdev** [comment]
lets go good work jason
