### ISSUE TITLE
Add the React Router to the Project

### ISSUE THREAD

**Issue by SilveerDusk** [SilveerDusk/Target-Share#9]
**Description**
Adds the react router to the project

**Acceptance Criteria**
idk

Steps:
idk

**Additional Information**
someone can add the details

**Comment by RahulSingh9131** [comment]
Assign me this issue, i am familiar with react router.

**Comment by SilveerDusk** [comment]
> Assign me this issue, i am familiar with react router.

Sorry Rahul this is a class project, not quite open source.
